#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Mar 06 18:39:30 EST 2025
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 9e6e68461b1a4f04899a6edc68238d7e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot ripple_adder_tb_behav xil_defaultlib.ripple_adder_tb -log elaborate.log"
xelab -wto 9e6e68461b1a4f04899a6edc68238d7e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot ripple_adder_tb_behav xil_defaultlib.ripple_adder_tb -log elaborate.log

